### ISSUE TITLE
Images for Groups

### ISSUE THREAD

**Issue by JoshuaRogan** [tccp/website#3]
Need content

**Comment by dslambrecht** [comment]
What's your experience as a web designer - do visitors prefer photos of the professor or a representative research figure?

**Comment by JoshuaRogan** [comment]
I think it really depends on the quality of the photos. If you have really high quality and resolution professor photos I think that would be ideal. I would go with whatever pictures you can get access to the highest quality. Plus, we can add the professor images and more on the interior pages of the groups.

**Comment by dslambrecht** [comment]
I'll ask what's available.
