### ISSUE TITLE
Make header smaller

### ISSUE THREAD

**Issue by dslambrecht** [tccp/website#4]
Can you remove the brain image? (or is that image imposed by jcubed)?

Can shorten the text to
The University of Pittsburgh has one of the largest groups of researchers engaged in Theoretical & 
Computational Chemistry research of any U. S. academic institution.

Use University seal instead of beaker
https://en.wikipedia.org/wiki/File:University_of_Pittsburgh_Seal_%28official%29.svg

**Comment by JoshuaRogan** [comment]
Nope they were essentially placeholders. Easy changes.
