### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by dslambrecht** [tccp/website#6]
Use Pitt's dark blue as header background
background: #002469
highlighted text: #ffdb96 <- use for title
standard text: #ffffff <- use for header paragraph

Keep current color scheme for the news bar
(we'll try out some variants later)

Main body:
White background, black for standard text
Use #002469 for paragraph headers

**Comment by JoshuaRogan** [comment]
![image](https://cloud.githubusercontent.com/assets/8824977/10182090/76b69f10-66ee-11e5-8c40-28ab5d8295e7.png)

**Comment by JoshuaRogan** [comment]
![image](https://cloud.githubusercontent.com/assets/8824977/10182101/9154db48-66ee-11e5-8cb4-d8bf810b21f1.png)
This is what it would look like with Pitt's color. The blue is really not good for backgrounds colors its way to sharp in my opinion. I would much prefer this: 

![image](https://cloud.githubusercontent.com/assets/8824977/10182147/e4108472-66ee-11e5-9184-54b34940b6e8.png)

Please let me know your thoughts. I understand if you want to keep it Pitt colors. I just am not a fan of that blue for web.
